--
-- PostgreSQL database dump
--

\restrict mc93V5svgBOEdATl50bKcQeetRCFJQjSxoFq4RT1atp5eRPYF2QgzTLtkfrd5Jl

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.0

-- Started on 2026-03-23 17:41:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 239 (class 1255 OID 24770)
-- Name: set_updated_at_now(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at_now() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 24614)
-- Name: career_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.career_roles (
    id integer NOT NULL,
    title character varying(150) NOT NULL,
    description text,
    entry_level boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 24613)
-- Name: career_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.career_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 24650)
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    session_id integer NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_chat_messages_role CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying])::text[])))
);


--
-- TOC entry 231 (class 1259 OID 24649)
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24644)
-- Name: chat_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(200),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 24643)
-- Name: chat_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 24658)
-- Name: interview_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_sessions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    role_id integer,
    mode character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    total_questions integer DEFAULT 5 NOT NULL,
    current_question_number integer DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'in_progress'::character varying NOT NULL,
    average_score numeric(3,2),
    completed_at timestamp without time zone,
    CONSTRAINT chk_average_score CHECK (((average_score IS NULL) OR ((average_score >= 1.0) AND (average_score <= 5.0)))),
    CONSTRAINT chk_mode CHECK (((mode)::text = ANY ((ARRAY['technical'::character varying, 'behavioral'::character varying, 'mixed'::character varying])::text[]))),
    CONSTRAINT chk_status CHECK (((status)::text = ANY ((ARRAY['in_progress'::character varying, 'completed'::character varying])::text[]))),
    CONSTRAINT chk_total_questions CHECK (((total_questions >= 3) AND (total_questions <= 10)))
);


--
-- TOC entry 233 (class 1259 OID 24657)
-- Name: interview_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24664)
-- Name: interview_turns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_turns (
    id integer NOT NULL,
    session_id integer NOT NULL,
    question text NOT NULL,
    user_answer text,
    ai_feedback text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    turn_number integer,
    ai_rating numeric(2,1),
    answered_at timestamp without time zone,
    CONSTRAINT chk_ai_rating CHECK (((ai_rating IS NULL) OR ((ai_rating >= 1.0) AND (ai_rating <= 5.0)))),
    CONSTRAINT chk_turn_number CHECK (((turn_number IS NULL) OR (turn_number > 0)))
);


--
-- TOC entry 235 (class 1259 OID 24663)
-- Name: interview_turns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_turns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_turns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24593)
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    user_id integer NOT NULL,
    full_name character varying(150),
    year_of_study integer,
    course character varying(150),
    interests text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    academic_focus character varying(150),
    preferred_technologies json,
    preferred_roles json
);


--
-- TOC entry 238 (class 1259 OID 24672)
-- Name: progress_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_entries (
    id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(50) NOT NULL,
    details json,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 24671)
-- Name: progress_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24636)
-- Name: recommendation_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_items (
    run_id integer NOT NULL,
    role_id integer NOT NULL,
    score numeric(6,3) NOT NULL,
    explanation text,
    competency_score double precision,
    preference_bonus double precision,
    final_score double precision
);


--
-- TOC entry 227 (class 1259 OID 24629)
-- Name: recommendation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_runs (
    id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    input_snapshot json,
    input_hash text,
    algo_version text DEFAULT 'v1'::text NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 24628)
-- Name: recommendation_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24623)
-- Name: role_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_skills (
    role_id integer NOT NULL,
    skill_id integer NOT NULL,
    required_level integer,
    importance integer,
    CONSTRAINT chk_role_skills_importance CHECK (((importance IS NULL) OR ((importance >= 1) AND (importance <= 5)))),
    CONSTRAINT chk_role_skills_required CHECK (((required_level IS NULL) OR ((required_level >= 1) AND (required_level <= 5))))
);


--
-- TOC entry 221 (class 1259 OID 24601)
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    category character varying(80)
);


--
-- TOC entry 220 (class 1259 OID 24600)
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24608)
-- Name: user_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_skills (
    user_id integer NOT NULL,
    skill_id integer NOT NULL,
    proficiency_level integer NOT NULL,
    evidence character varying(255),
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_user_skills_proficiency CHECK (((proficiency_level >= 1) AND (proficiency_level <= 5)))
);


--
-- TOC entry 218 (class 1259 OID 24584)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 24583)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4793 (class 2606 OID 24620)
-- Name: career_roles career_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career_roles
    ADD CONSTRAINT career_roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4795 (class 2606 OID 24622)
-- Name: career_roles career_roles_title_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career_roles
    ADD CONSTRAINT career_roles_title_key UNIQUE (title);


--
-- TOC entry 4809 (class 2606 OID 24656)
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 4806 (class 2606 OID 24648)
-- Name: chat_sessions chat_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 4815 (class 2606 OID 24662)
-- Name: interview_sessions interview_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 4819 (class 2606 OID 24670)
-- Name: interview_turns interview_turns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_turns
    ADD CONSTRAINT interview_turns_pkey PRIMARY KEY (id);


--
-- TOC entry 4821 (class 2606 OID 24844)
-- Name: interview_turns interview_turns_session_id_turn_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_turns
    ADD CONSTRAINT interview_turns_session_id_turn_number_key UNIQUE (session_id, turn_number);


--
-- TOC entry 4782 (class 2606 OID 24599)
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4824 (class 2606 OID 24678)
-- Name: progress_entries progress_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_entries
    ADD CONSTRAINT progress_entries_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 24642)
-- Name: recommendation_items recommendation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_items
    ADD CONSTRAINT recommendation_items_pkey PRIMARY KEY (run_id, role_id);


--
-- TOC entry 4801 (class 2606 OID 24635)
-- Name: recommendation_runs recommendation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_runs
    ADD CONSTRAINT recommendation_runs_pkey PRIMARY KEY (id);


--
-- TOC entry 4798 (class 2606 OID 24627)
-- Name: role_skills role_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_skills
    ADD CONSTRAINT role_skills_pkey PRIMARY KEY (role_id, skill_id);


--
-- TOC entry 4784 (class 2606 OID 24607)
-- Name: skills skills_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_name_key UNIQUE (name);


--
-- TOC entry 4786 (class 2606 OID 24819)
-- Name: skills skills_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_name_unique UNIQUE (name);


--
-- TOC entry 4788 (class 2606 OID 24605)
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 24612)
-- Name: user_skills user_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id);


--
-- TOC entry 4778 (class 2606 OID 24592)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4780 (class 2606 OID 24590)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4810 (class 1259 OID 24766)
-- Name: idx_chat_messages_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_messages_session_id ON public.chat_messages USING btree (session_id);


--
-- TOC entry 4807 (class 1259 OID 24765)
-- Name: idx_chat_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_sessions_user_id ON public.chat_sessions USING btree (user_id);


--
-- TOC entry 4811 (class 1259 OID 24840)
-- Name: idx_interview_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_sessions_status ON public.interview_sessions USING btree (status);


--
-- TOC entry 4812 (class 1259 OID 24839)
-- Name: idx_interview_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_sessions_user ON public.interview_sessions USING btree (user_id);


--
-- TOC entry 4813 (class 1259 OID 24767)
-- Name: idx_interview_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_sessions_user_id ON public.interview_sessions USING btree (user_id);


--
-- TOC entry 4816 (class 1259 OID 24845)
-- Name: idx_interview_turns_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_turns_session ON public.interview_turns USING btree (session_id);


--
-- TOC entry 4817 (class 1259 OID 24768)
-- Name: idx_interview_turns_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_interview_turns_session_id ON public.interview_turns USING btree (session_id);


--
-- TOC entry 4822 (class 1259 OID 24769)
-- Name: idx_progress_entries_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_progress_entries_user_id ON public.progress_entries USING btree (user_id);


--
-- TOC entry 4799 (class 1259 OID 24764)
-- Name: idx_recommendation_runs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_runs_user_id ON public.recommendation_runs USING btree (user_id);


--
-- TOC entry 4796 (class 1259 OID 24822)
-- Name: idx_role_skills_role_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_role_skills_role_id ON public.role_skills USING btree (role_id);


--
-- TOC entry 4789 (class 1259 OID 24823)
-- Name: idx_user_skills_user_skill; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_skills_user_skill ON public.user_skills USING btree (user_id, skill_id);


--
-- TOC entry 4802 (class 1259 OID 24821)
-- Name: uq_reco_runs_user_hash_version; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_reco_runs_user_hash_version ON public.recommendation_runs USING btree (user_id, input_hash, algo_version);


--
-- TOC entry 4839 (class 2620 OID 24771)
-- Name: profiles trg_profiles_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_now();


--
-- TOC entry 4840 (class 2620 OID 24772)
-- Name: user_skills trg_user_skills_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_user_skills_updated_at BEFORE UPDATE ON public.user_skills FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_now();


--
-- TOC entry 4834 (class 2606 OID 24808)
-- Name: chat_messages chat_messages_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id) ON DELETE CASCADE;


--
-- TOC entry 4833 (class 2606 OID 24788)
-- Name: chat_sessions chat_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4835 (class 2606 OID 24734)
-- Name: interview_sessions interview_sessions_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.career_roles(id);


--
-- TOC entry 4836 (class 2606 OID 24793)
-- Name: interview_sessions interview_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_sessions
    ADD CONSTRAINT interview_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4837 (class 2606 OID 24813)
-- Name: interview_turns interview_turns_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_turns
    ADD CONSTRAINT interview_turns_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.interview_sessions(id) ON DELETE CASCADE;


--
-- TOC entry 4825 (class 2606 OID 24773)
-- Name: profiles profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4838 (class 2606 OID 24798)
-- Name: progress_entries progress_entries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_entries
    ADD CONSTRAINT progress_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4831 (class 2606 OID 24714)
-- Name: recommendation_items recommendation_items_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_items
    ADD CONSTRAINT recommendation_items_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.career_roles(id);


--
-- TOC entry 4832 (class 2606 OID 24803)
-- Name: recommendation_items recommendation_items_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_items
    ADD CONSTRAINT recommendation_items_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.recommendation_runs(id) ON DELETE CASCADE;


--
-- TOC entry 4830 (class 2606 OID 24783)
-- Name: recommendation_runs recommendation_runs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_runs
    ADD CONSTRAINT recommendation_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4828 (class 2606 OID 24694)
-- Name: role_skills role_skills_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_skills
    ADD CONSTRAINT role_skills_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.career_roles(id);


--
-- TOC entry 4829 (class 2606 OID 24699)
-- Name: role_skills role_skills_skill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_skills
    ADD CONSTRAINT role_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- TOC entry 4826 (class 2606 OID 24689)
-- Name: user_skills user_skills_skill_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES public.skills(id);


--
-- TOC entry 4827 (class 2606 OID 24778)
-- Name: user_skills user_skills_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT user_skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-03-23 17:41:54

--
-- PostgreSQL database dump complete
--

\unrestrict mc93V5svgBOEdATl50bKcQeetRCFJQjSxoFq4RT1atp5eRPYF2QgzTLtkfrd5Jl

